

version:'3'

services: 

  backend:
    build: server/
    depends_on:
      - 'database'
    ports:
      - '3002:3002'

      
  database:
       build: server/database/
       context: ./server/database
       dockerfile: Dockerfile
     expose:
        - 5432
      environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres